name: Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: All things angular
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.4.0
      with:
        angular_project_dir: src/client/coodle
        github_access_token: ${{ secrets.COODLE_TOKEN }} 
        build_configuration: production 
        base_href: https://se22m007.github.io/coodle/
        deploy_branch: gh-pages
        angular_dist_build_folder: dist/coodle

permissions:
  contents: write 
